version: '3.8'

services:
  backend:
    build: .
    container_name: backend-inmobiliaria
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - db
    depends_on:
      - mysql

networks:
  db:
    external:
      name: inmobiliaria-vault
