services:
  backend:
    build: .
    container_name: backend-inmobiliaria
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - db

networks:
  db:
    external:
      name: inmobiliaria-vault
      external: true
