CREATE TABLE tbl_contract (
    id_contract                 INT AUTO_INCREMENT PRIMARY KEY,
    folio                       VARCHAR(50) NOT NULL,
    dt_start                    DATE  NOT NULL,
    dt_end                      DATE,
    monthly_rent                DECIMAL(10, 2) NOT NULL,
    security_deposit            DECIMAL(10, 2) NOT NULL,
    payment_day                 INT NOT NULL,
    penalty                     DECIMAL(10, 2),
    status                      ENUM('Activo','Vencido','Finalizado','Cancelado') DEFAULT 'Activo',
    id_landlord                 INT NOT NULL,
    id_tenant                   INT NOT NULL,
    id_property                 INT NOT NULL,
    guarantor_name              VARCHAR(100),
    guarantor_contact           VARCHAR(100),
    notes                       TEXT,
    fg_active	                INT(11) DEFAULT 1,
    id_user_last_modification   VARCHAR(255) DEFAULT NULL,
    dt_timestamp                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_contract_status) REFERENCES tbl_contract_status(id_contract_status),
    FOREIGN KEY (id_landlord) REFERENCES tbl_landlord(id_landlord),
    FOREIGN KEY (id_tenant) REFERENCES tbl_tenant(id_tenant),
    FOREIGN KEY (id_property) REFERENCES tbl_properties(id_property),
);